name: crm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  logger: ^2.0.2+1
  mask_text_input_formatter: ^2.6.0
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  cupertino_icons: ^1.0.6
  awesome_card: ^1.1.7
  flutter_bloc: ^8.1.3
  stylish_bottom_bar: ^1.0.3
  hidable: ^1.0.6
  lottie: ^2.7.0
  faker: ^2.1.0
  transformable_list_view: ^0.4.0
  filter_list: ^1.0.2
  flutter_native_splash: ^2.3.6
  flutter_svg: ^2.0.9
  scrollable_table_view: ^2.0.3
  pie_chart: ^5.4.0
  very_good_infinite_list: ^0.7.1
  translit: ^2.0.1
  ticket_widget: ^1.0.2
  awesome_extensions: ^2.0.10
  easy_localization: ^3.0.3
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo/splash/
    - assets/logo/app_image/
